version: "3.9"

services:
  db:
    image: postgres
    
    volumes:
      - db:/var/lib/postgresql/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    container_name: web
    command: sh -c "/code/startup.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db:
  