# Generated by Django 4.1.3 on 2024-03-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='room',
            field=models.IntegerField(blank=True, null=True, verbose_name='Room'),
        ),
    ]
