# Generated by Django 4.1.3 on 2024-03-17 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_remove_film_movie_genre_remove_film_movie_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='showtime',
            field=models.TimeField(default=datetime.datetime(2024, 3, 17, 12, 51, 8, 916685, tzinfo=datetime.timezone.utc), verbose_name='Showtime'),
        ),
    ]
