# Generated by Django 4.1.3 on 2024-03-17 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_show_showtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='showtime',
            field=models.TimeField(default=datetime.datetime(2024, 3, 17, 13, 0, 49, 5224, tzinfo=datetime.timezone.utc), verbose_name='Showtime'),
        ),
    ]
