# Generated by Django 4.1.3 on 2024-03-17 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_show_showtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='movie_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='movie_lang',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='film',
            name='movie_plot',
            field=models.TextField(blank=True, help_text='movie plot here ', null=True, verbose_name='Plot'),
        ),
        migrations.AddField(
            model_name='film',
            name='movie_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='show',
            name='room',
            field=models.IntegerField(choices=[(1, 'Blue'), (2, 'Red'), (3, 'Green')], default=1, verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='film',
            name='room',
            field=models.IntegerField(choices=[(1, 'Blue'), (2, 'Red'), (3, 'Green')], default=1, verbose_name='Room'),
        ),
        migrations.AlterField(
            model_name='show',
            name='showtime',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Showtime'),
        ),
    ]
