# Generated by Django 4.1.3 on 2024-03-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_film_movie_genre_film_movie_lang_film_movie_plot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='movie_genre',
        ),
        migrations.RemoveField(
            model_name='film',
            name='movie_lang',
        ),
        migrations.RemoveField(
            model_name='film',
            name='movie_plot',
        ),
        migrations.RemoveField(
            model_name='film',
            name='movie_year',
        ),
        migrations.AlterField(
            model_name='film',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Poster'),
        ),
    ]
